from fpdf import FPDF
import datetime
import os
import time
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email import encoders


class ForensicReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'PUMP-PATROL DIGITAL FORENSIC REPORT', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, 'CONFIDENTIAL // LAW ENFORCEMENT USE ONLY', 0, 1, 'C')
        self.ln(5)
        self.line(10, 30, 200, 30)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} - Generated by Pump Patrol AI', 0, 0, 'C')


def generate_pdf(scam_data):
    pdf = ForensicReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Metadata
    pdf.set_font("Arial", 'B', 12)
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    case_id = f"VI-{int(time.time())}"

    pdf.cell(200, 8, txt=f"CASE ID: #{case_id}", ln=1)
    pdf.cell(200, 8, txt=f"DATE OF INCIDENT: {timestamp}", ln=1)
    pdf.cell(200, 8, txt="DETECTING AGENT: Pump-Patrol Neural Engine v2.1", ln=1)
    pdf.ln(10)

    # Threat Analysis
    pdf.set_fill_color(200, 220, 255)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, txt=" THREAT ANALYSIS SUMMARY", ln=1, fill=True)
    pdf.ln(5)

    pdf.set_font("Arial", size=12)
    pdf.cell(200, 8, txt=f"Target Asset: {scam_data.get('stock', 'Unknown')}", ln=1)
    pdf.cell(200, 8, txt=f"Risk Level: {scam_data.get('status', 'Unknown')}", ln=1)
    pdf.cell(200, 8, txt=f"Hype Velocity: {scam_data.get('score', 0)}% (Abnormal)", ln=1)

    if "Opt:" in scam_data.get('stock', '') and "None" not in scam_data.get('stock', ''):
        pdf.set_text_color(255, 0, 0)
        pdf.cell(200, 8, txt="ALERT: DERIVATIVE MANIPULATION DETECTED", ln=1)
        pdf.set_text_color(0, 0, 0)
    pdf.ln(10)

    # Suspect Profile
    pdf.set_fill_color(255, 200, 200)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, txt=" PRIMARY SUSPECT / ORIGIN", ln=1, fill=True)
    pdf.ln(5)

    suspect_id = "Unknown / Distributed Botnet"
    messages = scam_data.get('messages', [])
    if messages:
        latest_msg = messages[0]
        if 'Sender ID' in latest_msg and latest_msg['Sender ID'] != 'Unknown':
            suspect_id = str(latest_msg['Sender ID'])

    pdf.set_font("Courier", 'B', 12)
    pdf.cell(200, 8, txt=f"TELEGRAM USER ID: {suspect_id}", ln=1)
    pdf.set_font("Arial", size=10)
    pdf.multi_cell(0, 5,
                   txt="(Note: This numeric ID is permanent and tracks the user even if they change their @username.)")
    pdf.ln(10)

    # Evidence Log
    pdf.set_fill_color(230, 230, 230)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, txt=" INTERCEPTED COMMUNICATIONS LOG", ln=1, fill=True)
    pdf.ln(5)

    pdf.set_font("Courier", size=10)
    for msg in messages:
        raw_text = str(msg.get('Message Text', ''))
        clean_text = raw_text.encode('latin-1', 'replace').decode('latin-1')
        group = str(msg.get('Group Name', 'Unknown')).encode('latin-1', 'replace').decode('latin-1')
        sender = str(msg.get('Sender ID', 'Unknown'))
        ts = str(msg.get('Timestamp', ''))

        pdf.set_font("Courier", 'B', 10)
        pdf.cell(0, 5, txt=f"[{ts}] GROUP: {group} | ID: {sender}", ln=1)
        pdf.set_font("Courier", size=10)
        pdf.multi_cell(0, 5, txt=f"MSG: {clean_text}")
        pdf.ln(3)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(3)

    if not os.path.exists('reports'):
        os.makedirs('reports')

    filename = f"reports/VI_CASE_{int(time.time())}.pdf"
    pdf.output(filename)
    return filename


def send_email_report(pdf_path, receiver_email):
    """
    Sends the generated PDF to the Cyber Cell (User's Email).
    """
    sender_email = "pump.patrol.system@gmail.com"  # Placeholder
    # password = "YOUR_APP_PASSWORD_HERE" # UNCOMMENT AND ADD PASSWORD FOR REAL MODE

    print(f"\n📧 [SMTP] PREPARING EMAIL TO: {receiver_email}")
    print(f"📎 [SMTP] ATTACHING EVIDENCE: {os.path.basename(pdf_path)}")

    # --- SIMULATION MODE (FOR DEMO SAFETY) ---
    # We simulate the delay and success to avoid login errors during presentation
    time.sleep(1.5)
    print(f"✅ [SMTP] EMAIL SENT SUCCESSFULLY TO {receiver_email}")
    return True

    # --- REAL MODE (Use this if you have credentials) ---
    # try:
    #     msg = MIMEMultipart()
    #     msg['From'] = sender_email
    #     msg['To'] = receiver_email
    #     msg['Subject'] = f"URGENT: Market Manipulation Detected - {os.path.basename(pdf_path)}"
    #     msg.attach(MIMEText("Forensic report attached. Automated dispatch.", 'plain'))
    #     with open(pdf_path, "rb") as attachment:
    #         part = MIMEBase("application", "octet-stream")
    #         part.set_payload(attachment.read())
    #     encoders.encode_base64(part)
    #     part.add_header("Content-Disposition", f"attachment; filename= {os.path.basename(pdf_path)}")
    #     msg.attach(part)
    #     server = smtplib.SMTP('smtp.gmail.com', 587)
    #     server.starttls()
    #     server.login(sender_email, password)
    #     server.send_message(msg)
    #     server.quit()
    #     return True
    # except Exception as e:
    #     print(f"❌ EMAIL FAILED: {e}")
    #     return False